services:
  redis:
    image: redis:8-alpine
    container_name: spy-bot-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-mypassword}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-mypassword}
    networks:
      - spy-bot-network

  app:
    build: .
    container_name: spy-bot-app
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - CACHE_TYPE=${CACHE_TYPE:-redis}
      - CACHE_TTL=${CACHE_TTL:-120}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-mypassword}@redis:6379
    depends_on:
      - redis
    networks:
      - spy-bot-network
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env

volumes:
  redis_data:

networks:
  spy-bot-network:
    driver: bridge
